### ISSUE TITLE
VST / AU Effect

### ISSUE THREAD

**Issue by stretta** [stretta/TextureExplorer#3]
Add the ability to insert VST effect into effects chain.

**Comment by mourendxu** [comment]
Hi, I tried to insert a VST3 version of Valhalla Supermassive into the FX chain using mc.vst~, and Max kept crashing.

It seems that due to the large # of channels in mc, Max would just die due to the large # of instantiations. I was able to make it work by using mcs.vst~. I had to put a mc.mixdown right before, just so all the slices will get into the effects.

So, I was wondering what are your thoughts/experience on this? Because given how heavy most vsts are compared to the effects written in Max, it would be nearly impossible to NOT have a mixdown section right before VSTs to lower the # of channels.

I tried a mixdown to 4 and instantiate mcs.vst with 4 input and output channels, and that worked without crashing.

Thank you!
